import { Bell, CheckCircle2, Coins, Gamepad2, LayoutDashboard, Radio, Send, ShieldAlert, Users, WalletCards, XCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { formatFaDecimal, formatFaNumber } from "@shared/format";

const statusLabels = { active: "فعال", maintenance: "تعمیر", disabled: "غیرفعال" } as const;
const txStatusLabels = { confirmed: "تأیید", failed: "رد", cancelled: "لغو" } as const;

function AdminStat({ icon: Icon, label, value }: { icon: typeof LayoutDashboard; label: string; value: number }) {
  return <article className="admin-stat glass-panel"><Icon size={19} /><span>{label}</span><strong>{formatFaNumber(value, { maximumFractionDigits: 0 })}</strong></article>;
}

function AdminPageContent() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const overviewQuery = trpc.admin.overview.useQuery(undefined, { enabled: isAdmin, refetchInterval: 15_000 });
  const sportsQuery = trpc.sports.fixtures.useQuery({ next: 10 }, { enabled: isAdmin, staleTime: 30_000 });
  const providerQuery = trpc.wallet.providerStatus.useQuery(undefined, { staleTime: 30_000 });
  const utils = trpc.useUtils();
  const [notification, setNotification] = useState({ target: "all" as "all" | "user", userId: "", type: "system" as "system" | "bet" | "wallet" | "reward" | "sports", title: "", message: "", href: "" });
  const [asset, setAsset] = useState({ code: "", name: "", symbol: "", decimals: "6", status: "maintenance" as "active" | "maintenance" | "disabled", networks: "", isBase: false });
  const notifyMutation = trpc.admin.notify.useMutation({ onSuccess: (data) => { toast.success(`اعلان برای ${formatFaNumber(data.count, { maximumFractionDigits: 0 })} کاربر ثبت شد.`); setNotification((current) => ({ ...current, title: "", message: "", href: "" })); void overviewQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const assetMutation = trpc.admin.assetUpsert.useMutation({ onSuccess: () => { toast.success("دارایی ذخیره شد."); setAsset({ code: "", name: "", symbol: "", decimals: "6", status: "maintenance", networks: "", isBase: false }); void overviewQuery.refetch(); void utils.assets.active.invalidate(); }, onError: (error) => toast.error(error.message) });
  const assetStatusMutation = trpc.admin.assetStatus.useMutation({ onSuccess: () => { void overviewQuery.refetch(); void utils.assets.active.invalidate(); }, onError: (error) => toast.error(error.message) });
  const gameStatusMutation = trpc.admin.gameStatus.useMutation({ onSuccess: () => { void overviewQuery.refetch(); void utils.games.catalog.invalidate(); }, onError: (error) => toast.error(error.message) });
  const promotionStatusMutation = trpc.admin.promotionStatus.useMutation({ onSuccess: () => { void overviewQuery.refetch(); void utils.promotions.active.invalidate(); }, onError: (error) => toast.error(error.message) });
  const reviewMutation = trpc.admin.reviewTransaction.useMutation({ onSuccess: () => { toast.success("وضعیت تراکنش ثبت شد."); void overviewQuery.refetch(); void utils.wallet.portfolio.invalidate(); void utils.wallet.transactions.invalidate(); }, onError: (error) => toast.error(error.message) });
  const overview = overviewQuery.data;

  if (!isAdmin) return <div className="admin-denied glass-panel"><ShieldAlert size={28} /><h1>دسترسی مدیریت لازم است</h1><p>این مسیر فقط برای نقش admin فعال است.</p></div>;
  if (overviewQuery.isLoading && !overview) return <div className="admin-loading glass-panel">در حال دریافت داده‌های مدیریت…</div>;
  if (overviewQuery.error) return <div className="admin-denied glass-panel"><ShieldAlert size={28} /><h1>پنل مدیریت در دسترس نیست</h1><p>{overviewQuery.error.message}</p><button className="solid-cta" onClick={() => void overviewQuery.refetch()}>تلاش دوباره</button></div>;
  if (!overview) return null;

  const submitNotification = () => {
    const userId = notification.target === "user" ? Number(notification.userId) : undefined;
    if (notification.target === "user" && (!Number.isInteger(userId) || !userId)) return toast.error("کاربر مقصد را انتخاب کن.");
    notifyMutation.mutate({ ...notification, userId, href: notification.href || undefined });
  };
  const submitAsset = () => assetMutation.mutate({ code: asset.code, name: asset.name, symbol: asset.symbol || asset.code, decimals: Number(asset.decimals), status: asset.status, networks: asset.networks.split(",").map((network) => network.trim()).filter(Boolean), isBase: asset.isBase });

  return <div className="admin-page" dir="rtl">
    <header className="admin-page-head"><div><span className="admin-overline">NEXUS CONTROL</span><h1>مرکز مدیریت</h1><p>کنترل داده‌های واقعی، اعلان‌ها و وضعیت عملیات.</p></div><span className="admin-role"><CheckCircle2 size={15} /> admin</span><span className={`admin-role ${providerQuery.data?.enabled ? "ready" : "pending"}`}><WalletCards size={15} /> provider: {providerQuery.isLoading ? "در حال بررسی" : providerQuery.data?.enabled ? "آماده" : "در انتظار secrets"}</span></header>
    <section className="admin-stat-grid" aria-label="خلاصهٔ مدیریت">
      <AdminStat icon={Users} label="کاربران" value={overview.counts.users} /><AdminStat icon={Coins} label="ارزهای فعال" value={overview.counts.activeAssets} /><AdminStat icon={Gamepad2} label="بازی‌های فعال" value={overview.counts.activeGames} /><AdminStat icon={Bell} label="تراکنش‌های در انتظار" value={overview.counts.pendingTransactions} />
    </section>
    <section className="admin-section glass-panel" id="notifications"><div className="admin-section-head"><div><Bell size={20} /><h2>اعلان سفارشی</h2></div><span>ثبت مستقیم در notifications</span></div><div className="admin-form-grid"><label><span>مقصد</span><select value={notification.target} onChange={(event) => setNotification({ ...notification, target: event.target.value as "all" | "user" })}><option value="all">همهٔ کاربران</option><option value="user">یک کاربر</option></select></label>{notification.target === "user" && <label><span>کاربر</span><select value={notification.userId} onChange={(event) => setNotification({ ...notification, userId: event.target.value })}><option value="">انتخاب کاربر</option>{overview.users.map((item) => <option value={item.id} key={item.id}>#{item.id} · {item.name ?? item.email ?? "بدون نام"}</option>)}</select></label>}<label><span>نوع</span><select value={notification.type} onChange={(event) => setNotification({ ...notification, type: event.target.value as typeof notification.type })}><option value="system">سیستم</option><option value="sports">ورزش</option><option value="wallet">کیف پول</option><option value="reward">پاداش</option><option value="bet">شرط</option></select></label><label><span>عنوان</span><input value={notification.title} maxLength={160} onChange={(event) => setNotification({ ...notification, title: event.target.value })} placeholder="مثلاً زمان‌بندی سرویس" /></label><label className="wide"><span>متن اعلان</span><textarea value={notification.message} maxLength={4000} onChange={(event) => setNotification({ ...notification, message: event.target.value })} placeholder="پیام کوتاه و دقیق برای کاربر…" /></label><label><span>مسیر داخلی (اختیاری)</span><input value={notification.href} maxLength={320} onChange={(event) => setNotification({ ...notification, href: event.target.value })} placeholder="/wallet" /></label></div><button className="solid-cta" disabled={notifyMutation.isPending || !notification.title.trim() || !notification.message.trim()} onClick={submitNotification}><Send size={16} /> {notifyMutation.isPending ? "در حال ثبت…" : "ارسال اعلان"}</button></section>
    <section className="admin-section glass-panel" id="assets"><div className="admin-section-head"><div><Coins size={20} /><h2>دارایی‌ها و شبکه‌ها</h2></div><span>USDT ارز پایه است؛ موجودی کاربر خودکار ساخته نمی‌شود.</span></div><div className="admin-asset-list">{overview.assets.map((item) => <article className="admin-row" key={item.id}><div><strong>{item.symbol}</strong><span>{item.name} · {item.networks.join("، ")}</span></div><span className={`admin-status ${item.status}`}>{statusLabels[item.status]}</span><div className="admin-row-actions">{(["active", "maintenance", "disabled"] as const).map((status) => <button key={status} className={item.status === status ? "selected" : ""} disabled={assetStatusMutation.isPending} onClick={() => assetStatusMutation.mutate({ assetId: item.id, status })}>{statusLabels[status]}</button>)}</div></article>)}</div><div className="admin-inline-form"><input value={asset.code} onChange={(event) => setAsset({ ...asset, code: event.target.value })} placeholder="کد BTC" /><input value={asset.name} onChange={(event) => setAsset({ ...asset, name: event.target.value })} placeholder="نام دارایی" /><input value={asset.symbol} onChange={(event) => setAsset({ ...asset, symbol: event.target.value })} placeholder="نماد" /><input value={asset.decimals} onChange={(event) => setAsset({ ...asset, decimals: event.target.value })} inputMode="numeric" placeholder="اعشار" /><input value={asset.networks} onChange={(event) => setAsset({ ...asset, networks: event.target.value })} placeholder="شبکه‌ها با ویرگول" /><select value={asset.status} onChange={(event) => setAsset({ ...asset, status: event.target.value as typeof asset.status })}><option value="active">فعال</option><option value="maintenance">تعمیر</option><option value="disabled">غیرفعال</option></select><button className="outline-cta" disabled={assetMutation.isPending} onClick={submitAsset}>ذخیره دارایی</button></div></section>
    <section className="admin-section glass-panel" id="operations"><div className="admin-section-head"><div><WalletCards size={20} /><h2>تراکنش‌های کیف پول</h2></div><span>{formatFaNumber(overview.counts.pendingTransactions, { maximumFractionDigits: 0 })} pending</span></div><div className="admin-table">{overview.transactions.length ? overview.transactions.map((transaction) => <div className="admin-row" key={transaction.id}><div><strong>{transaction.type} · {transaction.currency}</strong><span>کاربر #{transaction.userId} · {formatFaDecimal(transaction.amount)} · {transaction.network ?? "شبکه نامشخص"}</span></div><span className={`admin-status ${transaction.status}`}>{transaction.status}</span>{transaction.status === "pending" && <div className="admin-row-actions"><button onClick={() => reviewMutation.mutate({ transactionId: transaction.id, status: "confirmed" })}><CheckCircle2 size={14} /> تأیید</button><button onClick={() => reviewMutation.mutate({ transactionId: transaction.id, status: "failed" })}><XCircle size={14} /> رد</button></div>}</div>) : <p className="data-state">تراکنشی برای نمایش نیست.</p>}</div></section>
    <section className="admin-section glass-panel" id="catalog"><div className="admin-section-head"><div><Gamepad2 size={20} /><h2>catalog بازی و کمپین</h2></div><span>کنترل وضعیت انتشار</span></div><div className="admin-table">{overview.games.map((game) => <div className="admin-row" key={game.id}><div><strong>{game.title}</strong><span>{game.provider} · {game.slug}</span></div><span className={`admin-status ${game.status}`}>{statusLabels[game.status]}</span><div className="admin-row-actions">{(["active", "maintenance", "disabled"] as const).map((status) => <button key={status} className={game.status === status ? "selected" : ""} onClick={() => gameStatusMutation.mutate({ gameId: game.id, status })}>{statusLabels[status]}</button>)}</div></div>)}{overview.promotions.map((promotion) => <div className="admin-row" key={`promotion-${promotion.id}`}><div><strong>{promotion.title}</strong><span>کمپین · تا {new Date(promotion.endsAt).toLocaleDateString("fa-IR")}</span></div><span className={`admin-status ${promotion.status}`}>{promotion.status}</span><div className="admin-row-actions">{(["draft", "active", "expired"] as const).map((status) => <button key={status} className={promotion.status === status ? "selected" : ""} onClick={() => promotionStatusMutation.mutate({ promotionId: promotion.id, status })}>{status}</button>)}</div></div>)}</div></section>
    <section className="admin-section glass-panel" id="sports"><div className="admin-section-head"><div><Radio size={20} /><h2>فید ورزش‌ها</h2></div><span>{sportsQuery.isLoading ? "در حال دریافت…" : sportsQuery.data?.source === "api" ? "API واقعی" : "preview/fallback"}</span></div><div className="admin-feed-summary"><strong>{formatFaNumber(sportsQuery.data?.matches.length ?? 0, { maximumFractionDigits: 0 })}</strong><span>مسابقه در snapshot</span><p>{sportsQuery.data?.error ?? "آخرین snapshot از endpoint مسابقات دریافت شد."}</p></div></section>
  </div>;
}

export default function AdminPage() {
  return <DashboardLayout><AdminPageContent /></DashboardLayout>;
}
