import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Search, X, Zap } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { trpc } from "@/lib/trpc";
import { formatMatchKickoff, formatMatchOdds } from "@shared/sportsDisplay";
import { buildDemoDetail, type MatchCardData, type MatchDetailData } from "@shared/sports";
import { closeMatchModal, closesMatchModal, getMatchDetailsStatus, getTabEmptyMessage, matchModalTabs, openMatchModal, shouldCloseFromBackdrop, type MatchModalTab } from "@shared/matchModal";

const fallbackCards = [{ home: "رئال مادرید", homeLogo: "/manus-storage/real-madrid_189097ef.png", away: "بارسلونا", awayLogo: "/manus-storage/barcelona_36dcce68.png", hour: 22, minute: 30, league: "لالیگا", odds: [2.04, 3.62, 3.15] }, { home: "آرسنال", homeLogo: "/manus-storage/arsenal_81af535e.jpg", away: "چلسی", awayLogo: "/manus-storage/chelsea_7ee36ece.png", hour: 20, minute: 0, league: "لیگ برتر", odds: [2.28, 2.94, 4.2] }, { home: "بایرن مونیخ", homeLogo: "/manus-storage/bayern_70a7fa9c.png", away: "دورتموند", awayLogo: "/manus-storage/dortmund_990aaa2a.webp", hour: 20, minute: 0, league: "بوندس‌لیگا", odds: [1.76, 4.18, 4.75] }] as const;
function apiTime(time: string) {
  const [hour, minute] = time.split(":").map(Number);
  return Number.isFinite(hour) && Number.isFinite(minute) ? formatMatchKickoff(hour, minute) : time;
}

function ApiMatchCard({ match, onSelect }: { match: MatchCardData; onSelect: (match: MatchCardData, isApi: boolean) => void }) {
  return <article className="standalone-card glass-panel match-clickable" onClick={() => onSelect(match, true)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onSelect(match, true); }} role="button" tabIndex={0}><span className="sample-chip">{match.status} · {match.league}</span><div className="standalone-teams"><div><span className="sport-logo">{match.homeLogo ? <img src={match.homeLogo} alt="" /> : "⚽"}</span><b>{match.home}</b></div><strong>{match.score ?? apiTime(match.time)}{match.minute ? ` · ${match.minute}` : ""}</strong><div><span className="sport-logo">{match.awayLogo ? <img src={match.awayLogo} alt="" /> : "⚽"}</span><b>{match.away}</b></div></div><div className="market-preview"><span>{match.markets.length ? "بازارهای قابل انتخاب" : "بازارها"}</span>{match.markets.length ? match.markets.slice(0, 3).map((market) => <b key={market.name}>{market.label} {formatMatchOdds(market.odds)}</b>) : <small>در انتظار دریافت odds رسمی</small>}</div></article>;
}

function MatchDetailsModal({ match, isApi, onClose }: { match: MatchCardData; isApi: boolean; onClose: () => void }) {
  const detailsQuery = trpc.sports.details.useQuery({ fixtureId: match.id }, { enabled: isApi, staleTime: 60_000 });
  const apiDetails = detailsQuery.data;
  const details: MatchDetailData = !isApi ? buildDemoDetail(match) : apiDetails?.source === "api" ? apiDetails : { ...buildDemoDetail(match), source: "fallback", error: apiDetails?.error ?? "جزئیات واقعی در دسترس نیست." };
  const detailsStatus = getMatchDetailsStatus({ loading: detailsQuery.isLoading, error: detailsQuery.error ? "جزئیات واقعی در دسترس نیست؛ دادهٔ نمونه نمایش داده می‌شود." : details.source === "fallback" ? details.error : null, hasContent: details.statistics.length + details.lineups.length + details.events.length > 0, isDemo: details.source === "demo" });
  const [tab, setTab] = useState<MatchModalTab>("stats");
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (closesMatchModal(event.key)) onClose(); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [onClose]);
  return <div className="match-modal-backdrop" role="presentation" onMouseDown={(event) => { if (shouldCloseFromBackdrop(event.target, event.currentTarget)) onClose(); }}><section className="match-modal glass-panel" role="dialog" aria-modal="true" aria-labelledby="match-modal-title"><button className="modal-close" onClick={onClose} aria-label="بستن جزئیات"><X size={18} /></button><div className="modal-match-head"><span className="sample-chip">{isApi ? "دادهٔ API" : "دادهٔ نمونه"} · {match.league}</span><h2 id="match-modal-title">{match.home} <span>—</span> {match.away}</h2><p>{match.score ?? match.time}{match.minute ? ` · ${match.minute}` : ""}</p></div><div className="modal-tabs" role="tablist">{([ ["stats", "آمار بازی"], ["lineups", "ترکیب تیم‌ها"], ["events", "رویدادهای مهم"] ] as const).filter(([value]) => matchModalTabs.includes(value)).map(([value, label]) => <button key={value} role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}</button>)}</div>{detailsStatus === "loading" && <p className="modal-state">در حال دریافت جزئیات مسابقه…</p>}{detailsStatus === "error" && <p className="modal-state">{details.error ?? "جزئیات واقعی در دسترس نیست؛ دادهٔ نمونه نمایش داده می‌شود."}</p>}{detailsStatus === "demo" && <p className="modal-state">این جزئیات نمونه هستند و از سرویس واقعی دریافت نشده‌اند.</p>}{tab === "stats" && <div className="detail-stats">{details.statistics.length ? details.statistics.map((stat) => <div className="detail-stat-row" key={`${stat.label}-${stat.home}`}><span>{stat.home}</span><b>{stat.label}</b><span>{stat.away}</span></div>) : <p className="modal-state">{getTabEmptyMessage("stats")}</p>}</div>}{tab === "lineups" && <div className="detail-lineups">{details.lineups.length ? details.lineups.map((lineup) => <div className="lineup-column" key={lineup.team}><h3>{lineup.team} <small>{lineup.formation ?? ""}</small></h3>{lineup.players.map((player) => <div className="lineup-player" key={`${lineup.team}-${player.name}`}><span>{player.number ?? "—"}</span><b>{player.name}</b><small>{player.position}</small></div>)}</div>) : <p className="modal-state">{getTabEmptyMessage("lineups")}</p>}</div>}{tab === "events" && <div className="detail-events">{details.events.length ? details.events.map((event) => <div className="detail-event" key={`${event.minute}-${event.player}-${event.type}`}><b>{event.minute}</b><span><strong>{event.type}</strong> · {event.player}<small>{event.team}{event.detail ? ` · ${event.detail}` : ""}</small></span></div>) : <p className="modal-state">{getTabEmptyMessage("events")}</p>}</div>}</section></div>;
}

export default function Matches() {
  const sportsQuery = trpc.sports.fixtures.useQuery({ next: 10 }, { staleTime: 30_000, refetchInterval: 60_000 });
  const apiMatches = sportsQuery.data?.matches ?? [];
  const [selected, setSelected] = useState<{ match: MatchCardData; isApi: boolean } | null>(null);
  const fallbackMatches: MatchCardData[] = fallbackCards.map(({ home, homeLogo, away, awayLogo, hour, minute, league, odds }, index) => ({ id: `demo-${index}`, league, sport: "فوتبال", status: "نمونه", time: formatMatchKickoff(hour, minute), home, homeLogo, away, awayLogo, markets: odds.map((value, oddsIndex) => ({ label: ["۱", "X", "۲"][oddsIndex], name: "برد مستقیم", odds: value })), insight: "دادهٔ نمایشی" }));
  const shownMatches = apiMatches.length ? apiMatches : fallbackMatches;
  return <PageShell eyebrow="مرکز مسابقات" title="مسابقه‌ها، منظم و قابل‌فهم" description="دادهٔ مسابقات از API ورزشی دریافت می‌شود؛ اگر سرویس پاسخ ندهد، کارت‌های نمونه با برچسب روشن نمایش داده می‌شوند." heroImage="/manus-storage/nexus-bet-matches-hero-v2_fbfab850.png"><div className="subpage-toolbar"><label><Search size={16} /><input placeholder="جست‌وجوی تیم یا لیگ" /></label><button>همهٔ ورزش‌ها</button><button>فوتبال</button><span className={`sample-chip ${sportsQuery.data?.source === "api" ? "live-chip" : ""}`}>{sportsQuery.isLoading ? "در حال دریافت" : sportsQuery.data?.source === "api" ? "API واقعی" : "نمونه"}</span></div>{(sportsQuery.error || sportsQuery.data?.error) && <div className="inline-alert">{sportsQuery.data?.error ?? "اتصال به سرویس مسابقات برقرار نشد؛ دادهٔ نمونه برای حفظ تجربه نمایش داده می‌شود."}</div>}<div className="standalone-grid">{shownMatches.map((match) => <ApiMatchCard key={match.id} match={match} onSelect={(item) => setSelected({ match: item, isApi: openMatchModal(item.id, apiMatches.length > 0)?.isApi ?? false })} />)}</div><Link href="/crash" className="outline-cta">بازی انفجار را ببین <Zap size={16} /><ArrowLeft size={16} /></Link>{selected && <MatchDetailsModal match={selected.match} isApi={selected.isApi} onClose={() => { closeMatchModal(); setSelected(null); }} />}</PageShell>;
}
