import { Link } from "wouter";
import { ArrowDownLeft, ArrowLeft, ArrowUpRight, BrainCircuit, Check, Crown, Gift, LockKeyhole, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { formatFaDecimal } from "@shared/format";
import type { AiPick } from "@shared/ai";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

const usdt = (value: number) => formatFaDecimal(value);

export function WalletPage() { const { isAuthenticated } = useAuth(); const walletQuery = trpc.wallet.me.useQuery(undefined, { enabled: isAuthenticated }); const wallet = walletQuery.data; return <PageShell eyebrow="کیف پول USDT" title="دارایی‌ات، روشن و تحت کنترل" description="موجودی قابل‌استفاده، برداشت و شبکهٔ انتقال را یک‌جا ببین. آدرس واریز و برداشت تا اتصال ledger واقعی قابل استفاده نیست." heroImage="/manus-storage/nexus-bet-wallet-hero-v2_884a12f2.png"><div className="balance-hero glass-panel"><span>موجودی قابل‌استفاده</span><strong>{walletQuery.isLoading ? "در حال دریافت…" : wallet ? usdt(wallet.availableBalance) : "—"} <small>USDT</small></strong><div><span>قفل‌شده در شرط‌های باز</span><b>{wallet ? usdt(wallet.lockedBalance) : "—"} USDT</b></div>{!isAuthenticated && <p className="data-state">برای مشاهدهٔ موجودی واقعی وارد حساب شوید.</p>}{walletQuery.error && <p className="data-state error">موجودی واقعی در دسترس نیست.</p>}</div><div className="standalone-grid two"><article className="standalone-card glass-panel"><ArrowDownLeft /><h3>واریز</h3><p>TRC-20، TON و ERC-20 با هشدار شبکه و آدرس قابل کپی.</p><button className="solid-cta">انتخاب شبکه <ArrowLeft size={15} /></button></article><article className="standalone-card glass-panel"><ArrowUpRight /><h3>برداشت</h3><p>مبلغ، آدرس مقصد و وضعیت بررسی امنیتی را پیش از ثبت مرور کن.</p><button className="solid-cta">درخواست برداشت <ArrowLeft size={15} /></button></article></div></PageShell>; }

export function AiPage() { const sportsQuery = trpc.sports.fixtures.useQuery({ next: 10 }, { staleTime: 30_000 }); const candidates = (sportsQuery.data?.matches ?? []).flatMap((match) => match.markets.filter((market) => market.odds > 0).map((market, index) => ({ eventId: match.id, league: match.league, match: `${match.home} — ${match.away}`, sport: match.sport, marketLabel: market.label, marketName: market.name, odds: market.odds, status: match.status, popularity: Math.max(50, 90 - index * 8) }))); const aiQuery = trpc.ai.smartPicks.useQuery({ candidates }, { enabled: candidates.length > 0, staleTime: 60_000 }); return <PageShell eyebrow="NEXUS AI" title="پیشنهادها را بهتر بفهم" description="سیگنال‌های توضیح‌پذیر بر اساس فید مسابقات و بازارهای موجود؛ نه توصیهٔ قطعی و نه وعدهٔ سود." heroImage="/manus-storage/nexus-bet-ai-hero-v2_ad9c88ae.png"><div className="ai-callout glass-panel"><BrainCircuit size={23} /><div><b>تحلیل متصل به فید مسابقات</b><p>{sportsQuery.isLoading ? "در حال دریافت فید واقعی مسابقات…" : aiQuery.isLoading ? "در حال تحلیل بازارهای موجود…" : "پیشنهادها از دادهٔ فید فعلی ساخته می‌شوند."}</p></div><span className="sample-chip">غیرتضمینی</span></div>{sportsQuery.error || sportsQuery.data?.error ? <div className="inline-alert">فید واقعی در دسترس نیست؛ برای جلوگیری از ساخت پیشنهاد جعلی، نتیجه‌ای نمایش داده نمی‌شود.</div> : null}<div className="standalone-grid">{aiQuery.data?.picks.map((pick: AiPick) => <article className="ai-pick-card glass-panel" key={`${pick.eventId}-${pick.marketLabel}`}><div><Sparkles size={16} /><span>{pick.tags.join(" · ") || "تحلیل الگوریتمی"}</span></div><h3>{pick.marketName}</h3><p>{pick.match}</p><strong>{formatFaDecimal(pick.odds)}</strong><span className="risk-chip">ریسک {pick.risk} · اعتماد {formatFaDecimal(pick.confidence, 0)}٪</span><p>{pick.rationale}</p><button className="outline-cta" disabled>افزودن به بلیت <ArrowLeft size={15} /></button></article>)}</div>{!aiQuery.isLoading && !aiQuery.data?.picks.length && !sportsQuery.isLoading && <div className="empty-state glass-panel">برای این لحظه پیشنهاد قابل اتکایی از فید موجود تولید نشد.</div>}<p className="data-state">منبع: {aiQuery.data?.source === "ai" ? "Nexus AI روی فید مسابقات" : "fallback توضیح‌پذیر یا فید خالی"}. نتیجه تضمین‌شده نیست.</p></PageShell>; }

export function VipPage() { return <PageShell eyebrow="NEXUS VIP" title="فعال بمان، بیشتر دیده شو" description="سطح، امتیاز و مزایای VIP فقط پس از اتصال event ledger معتبر نمایش داده می‌شوند؛ این صفحه عدد ساختگی تولید نمی‌کند." heroImage="/manus-storage/nexus-bet-vip-hero-v2_6e37762c.png"><div className="vip-level glass-panel"><div><Crown size={24} /><span>وضعیت باشگاه</span><strong>در انتظار اتصال</strong></div><div><b>—</b><span>امتیاز فعالیت</span></div><div className="vip-progress"><span style={{ width: "0%" }} /><small>پس از ثبت فعالیت معتبر محاسبه می‌شود</small></div></div><div className="data-state preview-notice"><ShieldCheck size={15} /><span>مزایای VIP، امتیازها و وضعیت tier فعلاً پیش‌نمایش هستند و هیچ امتیاز یا مزیت عملیاتی به حساب اضافه نمی‌کنند.</span></div><div className="standalone-grid two">{[[Gift, "تحلیل ویژه Nexus AI", "پس از اتصال"], [WalletCards, "اولویت خدمات کیف پول", "پس از اتصال"], [LockKeyhole, "مزایای بنفش سلطنتی", "قفل"]].map(([Icon, title, state]) => <article className="standalone-card glass-panel" key={title as string}><Icon size={21} /><h3>{title as string}</h3><span className="locked-reward">{state as string}</span><p>قوانین و وضعیت نهایی این مزیت بعد از اتصال backend باشگاه نمایش داده می‌شود.</p></article>)}</div></PageShell>; }

export function AccountPage() { const { user, isAuthenticated } = useAuth(); const betsQuery = trpc.bet.mine.useQuery(undefined, { enabled: isAuthenticated }); const bets = betsQuery.data ?? []; const openBets = bets.filter((bet) => bet.status === "pending"); return <PageShell eyebrow="حساب کاربری" title="همه‌چیز دربارهٔ حساب تو" description="شرط‌های ثبت‌شده و وضعیت آن‌ها از backend خوانده می‌شوند؛ هیچ رکورد نمایشی به‌جای فعالیت واقعی نمایش داده نمی‌شود." heroImage="/manus-storage/nexus-bet-wallet_041598ee.jpg"><div className="account-summary glass-panel"><div className="avatar">N</div><div><b>{user?.name ?? "حساب Nexus"}</b><span>{isAuthenticated ? "فعالیت حساب از منبع واقعی" : "برای مشاهدهٔ فعالیت وارد حساب شوید."}</span></div><ShieldCheck size={21} /></div><div className="standalone-grid two"><article className="standalone-card glass-panel"><FileClockIcon /><h3>شرط‌های باز</h3><strong>{isAuthenticated ? `${openBets.length} بلیت فعال` : "—"}</strong>{openBets[0] ? <p>{openBets[0].selections[0]?.match ?? "انتخاب ثبت‌شده"} · ضریب {formatFaDecimal(openBets[0].combinedOdds)}</p> : <p>{betsQuery.isLoading ? "در حال دریافت…" : "هنوز بلیت ثبت‌شده‌ای وجود ندارد."}</p>}</article><article className="standalone-card glass-panel"><ShieldCheck /><h3>امنیت</h3><strong>حساب محافظت‌شده</strong><p>ورود امن، مدیریت محدودیت و پشتیبانی در یک مسیر.</p></article></div></PageShell>; }
function FileClockIcon() { return <LockKeyhole size={21} />; }
